### ISSUE TITLE
Пропуски моментов времени для отображения (timestamp)

### ISSUE THREAD

**Issue by Over328** [savelov/radar-wms#34]
https://www.nowcast.ru/RAD/demo.html# отображаются не все моменты времени, но на главной странице https://www.nowcast.ru/ всё нормально.
![2024-06-02_15-18-16](https://github.com/savelov/radar-wms/assets/134337440/b234bc9c-f776-43eb-b9b1-fa6c02b2c32e)

**Comment by savelov** [comment]
yes file processing was broken, fixing now

**Comment by Over328** [comment]
Thank you so much!
